"""Set up credentials from host into ~/.caw/auth/ and generate manifest + setup script."""

from __future__ import annotations

import textwrap
from pathlib import Path

from rich.console import Console

from .manifest import AgentManifest, Manifest
from .providers import PROVIDERS, AgentAuthProvider, CollectedFile

console = Console()

# Canonical auth directory
AUTH_DIR = Path.home() / ".caw" / "auth"


def _resolve_providers(agent_names: list[str]) -> list[AgentAuthProvider]:
    """Resolve provider names to provider objects."""
    if "all" in agent_names:
        return list(PROVIDERS.values())
    result = []
    for name in agent_names:
        if name not in PROVIDERS:
            available = ", ".join(PROVIDERS.keys())
            raise ValueError(f"Unknown agent '{name}'. Available: {available}")
        result.append(PROVIDERS[name])
    return result


def _validate_providers(
    providers: list[AgentAuthProvider], src_home: Path
) -> tuple[list[AgentAuthProvider], list[tuple[AgentAuthProvider, list[str]]]]:
    """Validate providers, returning (valid, skipped) lists."""
    valid = []
    skipped = []
    for provider in providers:
        missing = provider.validate(src_home)
        if missing:
            skipped.append((provider, missing))
        else:
            valid.append(provider)
    return valid, skipped


def _generate_setup_container_sh(manifest: Manifest) -> str:
    """Generate a standalone POSIX shell script for container-side setup."""
    return textwrap.dedent("""\
        #!/bin/sh
        # setup-container.sh — generated by `caw auth setup`
        # Sets up credential copies, config copies, and an inotify-based
        # bidirectional credential sync guard inside a container.
        # Usage: setup-container.sh <mount_point> <container_home> <username>
        set -e

        MOUNT_POINT="${1:-/tmp/caw_auth}"
        CONTAINER_HOME="${2:-/home/playground}"
        USERNAME="${3:-playground}"

        MANIFEST="$MOUNT_POINT/manifest.json"
        GUARD_PAIRS="/tmp/_caw_guard_pairs"
        GUARD_PID_FILE="/tmp/caw_credential_guard.pid"

        if [ ! -f "$MANIFEST" ]; then
            echo "[setup-container] ERROR: manifest.json not found at $MANIFEST"
            exit 1
        fi

        echo "[setup-container] Setting up auth files from $MOUNT_POINT..."

        # Clean up guard pairs file from any previous run
        rm -f "$GUARD_PAIRS"

        # Parse manifest with jq and process each file
        jq -r '
            .agents | to_entries[] | .value.files[] |
            [.src, .container_target, .strategy, .mode] | @tsv
        ' "$MANIFEST" | while IFS=$(printf '\\t') read -r src target strategy mode; do
            target_path="$CONTAINER_HOME/$target"
            source_path="$MOUNT_POINT/$src"

            # Create parent directory
            target_dir=$(dirname "$target_path")
            mkdir -p "$target_dir"

            if [ "$strategy" = "bind" ]; then
                # Credential files are bind-mounted from the host directly into
                # $MOUNT_POINT.  The setup script runs as root so it can read the
                # host-owned 0600 file; we copy it into the container user's home
                # (chowned to the container user) and start an inotify guard to
                # keep the two in sync.  Writes from the guard use plain `cp`,
                # which preserves the host inode's uid/gid/mode on the mount side.
                if [ ! -s "$source_path" ]; then
                    echo "[setup-container] ERROR: $source_path is empty or missing."
                    echo "[setup-container] Did you forget the credential file mount for $src?"
                    echo "[setup-container] Use \`caw auth docker-flags\` to get the full flag list."
                    exit 1
                fi
                rm -f "$target_path"
                cp "$source_path" "$target_path"
                chmod "$mode" "$target_path"
                chown "$USERNAME:$USERNAME" "$target_dir" 2>/dev/null || true
                chown "$USERNAME:$USERNAME" "$target_path" 2>/dev/null || true
                echo "[setup-container]   copy (credential): $target (mode $mode)"
                # Record source:local pair for the guard
                echo "$source_path|$target_path|$mode" >> "$GUARD_PAIRS"
            elif [ "$strategy" = "copy" ]; then
                cp "$source_path" "$target_path"
                chmod "$mode" "$target_path"
                chown "$USERNAME:$USERNAME" "$target_dir" 2>/dev/null || true
                chown "$USERNAME:$USERNAME" "$target_path" 2>/dev/null || true
                echo "[setup-container]   copy (config): $target (mode $mode)"
            fi
        done

        # -------------------------------------------------------------------
        # Credential guard — bidirectional sync via inotify
        # -------------------------------------------------------------------

        _caw_credential_guard() {
            PAIRS_FILE="$1"
            OWNER="$2"

            # Build inotifywait watch list: unique directories from both sides
            WATCH_DIRS=""
            while IFS='|' read -r src local _mode; do
                src_dir=$(dirname "$src")
                local_dir=$(dirname "$local")
                # Deduplicate by checking if already present
                case "$WATCH_DIRS" in
                    *"$src_dir"*) ;;
                    *) WATCH_DIRS="$WATCH_DIRS $src_dir" ;;
                esac
                case "$WATCH_DIRS" in
                    *"$local_dir"*) ;;
                    *) WATCH_DIRS="$WATCH_DIRS $local_dir" ;;
                esac
            done < "$PAIRS_FILE"

            echo "[credential-guard] Watching directories:$WATCH_DIRS"

            while true; do
                # shellcheck disable=SC2086
                inotifywait -m -q -e close_write $WATCH_DIRS 2>/dev/null | while read -r dir event filename; do
                    # dir has a trailing slash from inotifywait
                    changed_path="${dir}${filename}"

                    while IFS='|' read -r src local mode; do
                        if [ "$changed_path" = "$src" ]; then
                            # Source (bind mount) changed — sync to local copy
                            src_hash=$(md5sum "$src" 2>/dev/null | cut -d' ' -f1)
                            local_hash=$(md5sum "$local" 2>/dev/null | cut -d' ' -f1)
                            if [ "$src_hash" != "$local_hash" ]; then
                                cp "$src" "$local"
                                chmod "$mode" "$local"
                                chown "$OWNER:$OWNER" "$local" 2>/dev/null || true
                                echo "[credential-guard] synced $src -> $local"
                            fi
                        elif [ "$changed_path" = "$local" ]; then
                            # Local copy changed — sync back to bind mount
                            src_hash=$(md5sum "$src" 2>/dev/null | cut -d' ' -f1)
                            local_hash=$(md5sum "$local" 2>/dev/null | cut -d' ' -f1)
                            if [ "$src_hash" != "$local_hash" ]; then
                                cp "$local" "$src"
                                echo "[credential-guard] synced $local -> $src"
                            fi
                        fi
                    done < "$PAIRS_FILE"
                done
                echo "[credential-guard] inotifywait exited, restarting in 2s..."
                sleep 2
            done
        }

        # Start the guard if there are credential pairs to watch
        # Skip credential guard when using Bedrock (no credential sync needed)
        if [ "${CLAUDE_CODE_USE_BEDROCK:-0}" = "1" ]; then
            echo "[setup-container] Bedrock mode — skipping credential guard."
        elif [ -f "$GUARD_PAIRS" ] && [ -s "$GUARD_PAIRS" ]; then
            # Install inotify-tools if not present
            if ! command -v inotifywait >/dev/null 2>&1; then
                echo "[setup-container] Installing inotify-tools..."
                if apt-get update -qq >/dev/null 2>&1 && apt-get install -y -qq inotify-tools >/dev/null 2>&1; then
                    echo "[setup-container] inotify-tools installed."
                else
                    echo "[setup-container] WARNING: Failed to install inotify-tools. Credential guard will not run."
                    echo "[setup-container] Auth setup complete (without credential guard)."
                    exit 0
                fi
            fi

            # Kill any previous guard
            if [ -f "$GUARD_PID_FILE" ]; then
                old_pid=$(cat "$GUARD_PID_FILE" 2>/dev/null)
                if [ -n "$old_pid" ] && kill -0 "$old_pid" 2>/dev/null; then
                    kill "$old_pid" 2>/dev/null || true
                    echo "[setup-container] Stopped previous credential guard (PID $old_pid)."
                fi
                rm -f "$GUARD_PID_FILE"
            fi

            _caw_credential_guard "$GUARD_PAIRS" "$USERNAME" &
            echo $! > "$GUARD_PID_FILE"
            echo "[setup-container] Credential guard started (PID $(cat "$GUARD_PID_FILE"))."
        fi

        echo "[setup-container] Auth setup complete."
    """)


def setup(
    agents: list[str] | None = None,
    source_home: str | None = None,
    dest_dir: str | Path | None = None,
) -> Path:
    """Snapshot credentials and cleaned configs into an auth directory.

    Host credential files are read but not modified. At container run time
    they are bind-mounted into the same paths under the mount point — see
    :func:`caw.auth.get_docker_flags`.

    Args:
        agents: List of agent names, or None / ["all"] for all agents.
        source_home: Home directory to read credentials from.
        dest_dir: Custom destination directory. Defaults to ~/.caw/auth/.

    Returns:
        Path to the auth directory.
    """
    src_home = Path(source_home) if source_home else Path.home()
    auth_dir = Path(dest_dir) if dest_dir else AUTH_DIR

    console.print(f"[bold]Collecting credentials into {auth_dir}/[/bold]\n")

    # Resolve providers
    selected = _resolve_providers(agents or ["all"])

    # Validate
    valid_providers, skipped_providers = _validate_providers(selected, src_home)

    if not valid_providers:
        console.print("[red]Error: No valid agent credentials found.[/red]")
        for provider, missing in skipped_providers:
            console.print(f"  [dim]{provider.name}:[/dim] missing {', '.join(missing)}")
        raise SystemExit(1)

    # Warn about missing agents
    if skipped_providers:
        for provider, missing in skipped_providers:
            console.print(f"[yellow]Warning: {provider.name} credentials not found:[/yellow] {', '.join(missing)}")
        console.print()

    # Show what we'll process
    names = [p.name for p in valid_providers]
    console.print(f"[dim]Agents:[/dim] {', '.join(names)}\n")

    # Describe each provider
    for provider in valid_providers:
        desc = provider.describe(src_home)
        console.print(f"[bold]{provider.name}:[/bold] {desc}")
    console.print()

    # Collect files from all providers
    all_files: list[CollectedFile] = []
    manifest = Manifest.create(host_home=str(src_home))

    for provider in valid_providers:
        console.print(f"[bold]Collecting {provider.name} files...[/bold]")
        collected = provider.collect(src_home)
        all_files.extend(collected)

        # Build manifest entry
        agent_manifest = AgentManifest(files=[cf.manifest_file for cf in collected])
        manifest.agents[provider.name] = agent_manifest

    # Write everything
    if auth_dir.exists():
        import shutil

        shutil.rmtree(auth_dir)
    auth_dir.mkdir(parents=True)

    # Write collected files
    for cf in all_files:
        out_path = auth_dir / cf.manifest_file.src
        out_path.parent.mkdir(parents=True, exist_ok=True)
        out_path.write_bytes(cf.content)
        out_path.chmod(int(cf.manifest_file.mode, 8))

    # Write manifest
    manifest.save(auth_dir / "manifest.json")

    # Write setup-container.sh
    setup_script = auth_dir / "setup-container.sh"
    setup_script.write_text(_generate_setup_container_sh(manifest))
    setup_script.chmod(0o755)

    # Set directory permissions
    for d in auth_dir.rglob("*"):
        if d.is_dir():
            d.chmod(0o755)

    console.print("\n[bold green]Done![/bold green]")
    console.print(f"Auth files written to: {auth_dir}")
    console.print("\n[dim]Contents:[/dim]")
    for cf in all_files:
        strategy = cf.manifest_file.strategy
        ftype = cf.manifest_file.type
        console.print(f"  [dim]{cf.manifest_file.src}[/dim]  ({ftype}, {strategy})")
    console.print("  [dim]manifest.json[/dim]")
    console.print("  [dim]setup-container.sh[/dim]")
    console.print(
        "\n[dim]Host credential files are untouched; they will be bind-mounted "
        "into the container at run time. Use `caw auth docker-flags` to get the "
        "full -v flag list.[/dim]"
    )

    return auth_dir
